<a href="https://colab.research.google.com/github/theAkhileshRai/Projects/blob/master/LabelSequencing2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import glob
import csv

In [0]:
smalltest_df = pd.read_csv('/content/drive/My Drive/smalltest.csv')

In [0]:
smalltest_df.head()

   Unnamed: 0  ...  FillagePercent
0           0  ...             100
1           1  ...             100
2           2  ...              22
3           3  ...              77
4           4  ...             100

[5 rows x 804 columns]

In [0]:
down_stroke_df = pd.read_csv('/content/DownStrokePatterns_old.csv')

In [0]:
down_stroke_df.columns = down_stroke_df.columns.str.strip()
len(down_stroke_df.columns)

113

In [0]:
down_stroke_df['pump condition'].unique()

array([' FULLPUMP', ' FLUIDPOUND', ' GASINTERFERENCE',
       ' INCOMPLETEFILLAGE'], dtype=object)

In [0]:
#Label Encoder

In [0]:
down_stroke_df.columns

Index(['index', 'title', 'pump fillage', 'bottom horizontal line setting',
       'pump condition', 'standing valve or plunger leak',
       'pumping hitting down', 'malfunctioning tubing-anchor',
       'bent or sticking pump barrel', 'worn or split pump barrel',
       ...
       'load(89)', 'load(90)', 'load(91)', 'load(92)', 'load(93)', 'load(94)',
       'load(95)', 'load(96)', 'load(97)', 'load(98)'],
      dtype='object', length=113)

In [0]:
down_stroke_df.loc[:,'load(0)':].head()

   load(0)  load(1)  load(2)  load(3)  ...  load(95)  load(96)  load(97)  load(98)
0     2738     1882     1025     1023  ...       438       378      1677      2976
1     3224     2194     1164     1011  ...      7398      7800      8144      8487
2    10000     7304     4607     4702  ...      6382      6216      6682      7148
3     6984     4010     1035     1048  ...       386       409      1584      2760
4     2459     1923     1387     1356  ...      2384      4356      6562      8768

[5 rows x 99 columns]

In [0]:
down_stroke_labelled = down_stroke_df.loc[:,'load(0)':].to_numpy().astype(np.float)

In [0]:
down_stroke_labelled

array([[ 2738.,  1882.,  1025., ...,   378.,  1677.,  2976.],
       [ 3224.,  2194.,  1164., ...,  7800.,  8144.,  8487.],
       [10000.,  7304.,  4607., ...,  6216.,  6682.,  7148.],
       ...,
       [ 1609.,  1575.,  1457., ...,  4495.,  6995.,  8182.],
       [ 3386.,  2299.,  1457., ...,  4495.,  6995.,  8182.],
       [    0.,   830.,   874., ...,  6050.,  6214.,  7574.]])

In [0]:
downstroke_gen_df = pd.read_csv("/content/Downstroke_gen.csv")

In [0]:
downstroke_gen_df.head()

   Unnamed: 0                                         Downstroke
0           0  [4.27201056 4.22841862 4.18482667 4.14123473 4...
1           1  [7923.58500894 7909.91899442 7910.12007474 791...
2           2  [4.25490132        nan        nan        nan  ...
3           3  [9.75881779        nan        nan        nan  ...
4           4  [13.85809313         nan         nan         n...

In [0]:
downstroke_array = []
for i in range(len(downstroke_gen_df['Downstroke'])):
  s = downstroke_gen_df['Downstroke'][i]
  s = s.replace("[", "").replace("]", "")
  s = s.replace(",", " ")
  a = s.split()
  downstroke_array.append(s.split())

In [0]:
downstroke_array = np.array(downstroke_array).astype(np.float)

In [0]:
len(downstroke_array[0])

99

In [0]:
len(down_stroke_labelled)

3028

In [0]:
from sklearn.semi_supervised import LabelSpreading
label_test = np.copy(down_stroke_labelled)

In [0]:
label_prop_model = LabelSpreading(kernel = 'rbf',n_neighbors=4,alpha = 0.3)

In [0]:
rng = np.random.RandomState(42)

In [0]:
downstroke_array.shape

(2000, 99)

In [0]:
down_stroke_labelled.shape

(3028, 99)

In [0]:
label_prop_model.fit(label_test, downstroke_array)

ValueError: ignored

In [0]:
from sklearn import datasets
from sklearn.semi_supervised import LabelPropagation
label_prop_model = LabelPropagation()
iris = datasets.load_iris()
rng = np.random.RandomState(42)
random_unlabeled_points = rng.rand(len(iris.target)) < 0.3
labels = np.copy(iris.target)
labels[random_unlabeled_points] = -1

In [0]:
iris.data.shape

In [0]:

len(random_unlabeled_points)

In [0]:
label_prop_model.fit(iris.data, labels)

In [0]:
labels